### ISSUE TITLE
Add type classes

### ISSUE THREAD

**Issue by Qbxs** [duo-lang/duo-lang#356]
A minimum viable product should support monotypes (`Bool`, `Nat`, etc.). The syntax could look like this:

```
-- | Class definition.
class Eq(+a CBV) {
  Equals(a, a, return Bool)
};

-- | Instance definition.
instance Eq Bool {
  Equals(x, y, k) => ...
};

-- | Usage as overloading without generalisations.
def prd foo : Bool := mu k. Equals(True, False,k);

-- | Usage with type class constraint.
def rec prd elem : forall a. (Eq a) => a -> List(a) -> Bool :=
  \e l => case l of {
        Nil => False,
        Cons(x, xs) => or Equals(e, x, *) (elem e xs)
    };
```

The implementation would be based on implicit dictionary passing like in Haskell98 as described [here](https://okmij.org/ftp/Computation/typeclass.html)

### Declarations

- [x]  Implement syntax: parser and pretty-printer (done in: #357 )
- [x] Implement resolver (done in: #367 & #378)
- [x] Implement focusing (done in: #389)
- [x] Implement locally closed checking for instances (done in: #384)
- [x] Check bound variables in class declaration (done in: #384)
- [x] Implement type checking of instance definitions (done in: #380)

### Terms

- [x] Implement type checking for type class method calls (done in: #385)
- [x] Implement evaluation (partially done in: #514)
- [ ] Add type class constraints to type schemes
